FROM ubuntu:20.10

WORKDIR /usr/src/app

RUN apt update && apt install -y git curl unzip

RUN git clone https://github.com/flutter/flutter.git /flutter
ENV PATH "$PATH:/flutter/bin"

RUN flutter channel stable
RUN flutter doctor

RUN mkdir /build
RUN echo '{ "build-dir": "../../../build" }' > /root/.flutter_settings

CMD ['flutter pub get ; flutter build web']
