version: "3.7"

services:
    scheduler:
        image: ghcr.io/htchan/web-history:scheduler-beta
        hostname: webhostory_scheduler
        volumes:
            - ./bin/logs:/logs
            - ./backend/database/migrations:/migrations
        networks:
            - database
        env_file:
            - ./backend/assets/.env.scheduler

    api:
        image: ghcr.io/htchan/web-history:api-latest
        deploy:
            resources:
                limits:
                    memory: '100M'
        hostname: webhistory_backend
        volumes:
            - ./bin/database:/database
            - ./bin/logs:/logs
            - ./backend/database/migrations:/migrations
        networks:
            - router
            - database
        profiles:
            - all
            - api
            - web
        ports:
            - 9105:9105
        env_file:
            - ./backend/assets/.env.backend

    worker:
        image: ghcr.io/htchan/web-history:worker-latest
        deploy:
            resources:
                limits:
                    memory: '25M'
        hostname: webhistory_worker
        volumes:
            - ./bin/database:/database
            - ./bin/logs:/logs
            - ./backend/database/migrations:/migrations
        networks:
            - database
            - trace
        profiles:
            - all
            - worker
        env_file:
            - ./backend/assets/.env.worker

    backup:
        build:
            context: ./backup
            dockerfile: ./Dockerfile
        volumes:
            - ./bin/backup:/backup
        networks:
            - database
        profiles:
            - all
            - backup
        env_file:
            - ./.env

    frontend:
        build:
            context: ./frontend
        volumes:
            - frontend_volume:/build/web
            - ./frontend/src:/usr/src/app
        networks:
            - router
        profiles:
            - all
            - frontend
            - web
        env_file:
            - ./frontend/src/.env
        # command: sh -c "
        #     flutter --version ; 
        #     flutter pub get ; 
        #     flutter build web  --base-href $WEB_WATCHER_FE_ROUTE_PREFIX/ \
        #     --dart-define=WEB_WATCHER_API_HOST=$WEB_WATCHER_API_HOST \
        #     --dart-define=WEB_WATCHER_API_ROUTE_PREFIX=$WEB_WATCHER_API_ROUTE_PREFIX \
        #     --dart-define=WEB_WATCHER_FE_ROUTE_PREFIX=$WEB_WATCHER_FE_ROUTE_PREFIX"
        command: sh -c "flutter --version ; flutter pub get ; flutter build web --base-href $WEB_WATCHER_FE_ROUTE_PREFIX/"

volumes:
    frontend_volume:
        name: webhistory_frontend_volume

networks:
    router:
        driver: bridge
        name: router
    database:
        name: database
        external: true
    trace:
        name: trace
        external: true
